### ISSUE TITLE
pgvector-haystack cannot be installed from psycopg on 3.1.20

### ISSUE THREAD

**Issue by phiweger** [deepset-ai/haystack-core-integrations#1267]
`pgvector-haystack` depends on `psycopg[binary]` but [psycopg-binary can't be installed with M1 CPU starting from 3.1.20](https://github.com/psycopg/psycopg/issues/858). Instead, `psycopg[c]` works, which is the ["local installation"](https://www.psycopg.org/psycopg3/docs/basic/install.html#local-installation), which is also recommended:

> This is the preferred way to install Psycopg for a production site.

Is this something you'd consider changing?

**Comment by phiweger** [comment]
A workaround for people encountering this is to override the dependency spec of `pgvector-haystack` using the `uv` package manager:

```toml
[project]
name = "foo"
version = "0.0.1"
description = "bar"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pgvector-haystack==1.2.0",
]

[[tool.uv.dependency-metadata]]
name = "pgvector-haystack"
version = "1.2.0"
requires-dist = ["haystack-ai", "pgvector", "psycopg[c]==3.2.3"]
```
