### ISSUE TITLE
Weaviate: `timeout_config` is not serialized properly

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#523]
**Describe the bug**
`timeout_config` is a tuple and it is not serialized properly using `Pipeline.dumps`.
This causes the subsequent deserialization from YAML to fail.

**To Reproduce**
```python
from haystack_integrations.document_stores.weaviate.document_store \
    import WeaviateDocumentStore
from haystack import Pipeline
from haystack.components.writers import DocumentWriter


document_store = WeaviateDocumentStore(url="http://localhost:8080")

pipe = Pipeline()
pipe.add_component("writer", DocumentWriter(document_store))

serialized_pipe = pipe.dumps()
print(serialized_pipe)

deserialized_pipe = Pipeline.loads(serialized_pipe)
```

Error:
```
  File "/home/anakin87/.virtualenvs/llms4devs/lib/python3.10/site-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/tuple'
  in "<unicode string>", line 35, column 27:
              timeout_config: !!python/tuple
```

**YAML**
```yaml
components:
  writer:
    init_parameters:
      document_store:
        init_parameters:
          additional_config: null
          ...
          timeout_config: !!python/tuple
          - 10
          - 60
          ...
        type: haystack_integrations.document_stores.weaviate.document_store.WeaviateDocumentStore
      policy: NONE
    type: haystack.components.writers.document_writer.DocumentWriter
...
```

**Describe your environment (please complete the following information):**
 - Haystack version: 2.0-beta8
 - Integration version: Weaviate == 1.0.2
